spring.application.name=demo

# Veritaban? ba?lant? bilgileri
spring.datasource.url=jdbc:postgresql://localhost:5432/ik_projesi
spring.datasource.username=ik_user
spring.datasource.password=12345

# Hibernate'e tablolar? otomatik olu?turma yetkisi veriyoruz
spring.jpa.hibernate.ddl-auto=update

# Arka planda çal??an SQL kodlar?n? görmek için
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true